name: stellar-lab
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2.0
  - pandas<2.0
  - scipy
  - plotly
  - ipywidgets
  - anywidget
  - pip
  - pip:
    - git+https://github.com/mfouesneau/ezmist.git
