name: isochrone-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - numba
  - pytables
  - plotly
  - ipywidgets
  - anywidget
  - pip
  - pip:
    - isochrones
